ALTER TYPE "PayrollStatus" ADD VALUE 'ATTENDANCE_LOCKED';
ALTER TYPE "PayrollStatus" ADD VALUE 'CALCULATED';
ALTER TYPE "PayrollStatus" ADD VALUE 'HR_REVIEW';
ALTER TYPE "PayrollStatus" ADD VALUE 'FINANCE_APPROVED';
ALTER TYPE "PayrollStatus" ADD VALUE 'LOCKED';
ALTER TYPE "PayrollStatus" ADD VALUE 'PAYSLIPS_PUBLISHED';
ALTER TYPE "PayrollStatus" ADD VALUE 'BANK_EXPORTED';
ALTER TYPE "PayrollStatus" ADD VALUE 'REVERSED';
CREATE TYPE "SalaryComponentKind" AS ENUM ('EARNING','DEDUCTION','EMPLOYER_CONTRIBUTION','REIMBURSEMENT');
CREATE TYPE "SalaryCalculationMethod" AS ENUM ('FIXED','PERCENT_BASIC','PERCENT_GROSS');
CREATE TYPE "SalaryRevisionStatus" AS ENUM ('DRAFT','PENDING','APPROVED','REJECTED','SUPERSEDED');
CREATE TYPE "StatutoryRuleType" AS ENUM ('PF','ESI','PROFESSIONAL_TAX','TDS','LWF');
CREATE TYPE "EmployeeLoanStatus" AS ENUM ('DRAFT','ACTIVE','CLOSED','WAIVED');
CREATE TYPE "TaxDeclarationStatus" AS ENUM ('DRAFT','SUBMITTED','VERIFIED','REJECTED');
CREATE TYPE "InvestmentProofStatus" AS ENUM ('PENDING','VERIFIED','REJECTED');
CREATE TYPE "SettlementStatus" AS ENUM ('DRAFT','CALCULATED','APPROVED','PAID','REVERSED');

ALTER TABLE "PayrollRun" ADD COLUMN "periodStart" DATE, ADD COLUMN "periodEnd" DATE, ADD COLUMN "attendanceLockId" TEXT,
 ADD COLUMN "calculatedAt" TIMESTAMP(3), ADD COLUMN "hrReviewedById" TEXT, ADD COLUMN "hrReviewedAt" TIMESTAMP(3),
 ADD COLUMN "financeApprovedById" TEXT, ADD COLUMN "financeApprovedAt" TIMESTAMP(3), ADD COLUMN "lockedById" TEXT,
 ADD COLUMN "lockedAt" TIMESTAMP(3), ADD COLUMN "reversedRunId" TEXT, ADD COLUMN "bankExportedAt" TIMESTAMP(3),
 ADD COLUMN "workflowInstanceId" TEXT, ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE TABLE "SalaryStructure" ("id" TEXT NOT NULL,"companyId" TEXT NOT NULL,"name" TEXT NOT NULL,"code" TEXT NOT NULL,"description" TEXT,"active" BOOLEAN NOT NULL DEFAULT true,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "SalaryStructure_pkey" PRIMARY KEY("id"));
CREATE TABLE "SalaryStructureComponent" ("id" TEXT NOT NULL,"structureId" TEXT NOT NULL,"code" TEXT NOT NULL,"name" TEXT NOT NULL,"kind" "SalaryComponentKind" NOT NULL,"method" "SalaryCalculationMethod" NOT NULL DEFAULT 'FIXED',"value" DOUBLE PRECISION NOT NULL,"taxable" BOOLEAN NOT NULL DEFAULT true,"proratable" BOOLEAN NOT NULL DEFAULT true,"statutoryType" "StatutoryRuleType","sequence" INTEGER NOT NULL DEFAULT 0,CONSTRAINT "SalaryStructureComponent_pkey" PRIMARY KEY("id"));
CREATE TABLE "EmployeeSalaryRevision" ("id" TEXT NOT NULL,"companyId" TEXT NOT NULL,"employeeId" TEXT NOT NULL,"structureId" TEXT NOT NULL,"effectiveFrom" DATE NOT NULL,"annualCtc" DOUBLE PRECISION NOT NULL,"componentValues" JSONB,"reason" TEXT,"status" "SalaryRevisionStatus" NOT NULL DEFAULT 'DRAFT',"workflowInstanceId" TEXT,"approvedById" TEXT,"approvedAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "EmployeeSalaryRevision_pkey" PRIMARY KEY("id"));
CREATE TABLE "StatutoryRuleVersion" ("id" TEXT NOT NULL,"companyId" TEXT NOT NULL,"type" "StatutoryRuleType" NOT NULL,"jurisdiction" TEXT NOT NULL DEFAULT 'IN',"stateCode" TEXT,"effectiveFrom" DATE NOT NULL,"effectiveTo" DATE,"configuration" JSONB NOT NULL,"sourceNote" TEXT,"active" BOOLEAN NOT NULL DEFAULT true,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "StatutoryRuleVersion_pkey" PRIMARY KEY("id"));
CREATE TABLE "EmployeeLoan" ("id" TEXT NOT NULL,"companyId" TEXT NOT NULL,"employeeId" TEXT NOT NULL,"type" TEXT NOT NULL,"principal" DOUBLE PRECISION NOT NULL,"outstanding" DOUBLE PRECISION NOT NULL,"installment" DOUBLE PRECISION NOT NULL,"interestRate" DOUBLE PRECISION NOT NULL DEFAULT 0,"startsOn" DATE NOT NULL,"status" "EmployeeLoanStatus" NOT NULL DEFAULT 'DRAFT',"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "EmployeeLoan_pkey" PRIMARY KEY("id"));
CREATE TABLE "LoanRepayment" ("id" TEXT NOT NULL,"loanId" TEXT NOT NULL,"payrollRunId" TEXT,"amount" DOUBLE PRECISION NOT NULL,"paidAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "LoanRepayment_pkey" PRIMARY KEY("id"));
CREATE TABLE "PayrollAdjustment" ("id" TEXT NOT NULL,"companyId" TEXT NOT NULL,"employeeId" TEXT NOT NULL,"month" TEXT NOT NULL,"code" TEXT NOT NULL,"name" TEXT NOT NULL,"kind" "SalaryComponentKind" NOT NULL,"amount" DOUBLE PRECISION NOT NULL,"reason" TEXT NOT NULL,"createdById" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "PayrollAdjustment_pkey" PRIMARY KEY("id"));
CREATE TABLE "PayrollLine" ("id" TEXT NOT NULL,"payrollRunId" TEXT NOT NULL,"employeeId" TEXT NOT NULL,"workingDays" DOUBLE PRECISION NOT NULL,"payableDays" DOUBLE PRECISION NOT NULL,"unpaidDays" DOUBLE PRECISION NOT NULL,"grossEarnings" DOUBLE PRECISION NOT NULL,"employeeDeductions" DOUBLE PRECISION NOT NULL,"employerContributions" DOUBLE PRECISION NOT NULL,"reimbursements" DOUBLE PRECISION NOT NULL,"netPay" DOUBLE PRECISION NOT NULL,"breakdown" JSONB NOT NULL,"calculationTrace" JSONB NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "PayrollLine_pkey" PRIMARY KEY("id"));
CREATE TABLE "TaxDeclaration" ("id" TEXT NOT NULL,"companyId" TEXT NOT NULL,"employeeId" TEXT NOT NULL,"financialYear" TEXT NOT NULL,"regime" TEXT NOT NULL DEFAULT 'NEW',"declarations" JSONB NOT NULL,"totalDeclared" DOUBLE PRECISION NOT NULL DEFAULT 0,"totalVerified" DOUBLE PRECISION NOT NULL DEFAULT 0,"status" "TaxDeclarationStatus" NOT NULL DEFAULT 'DRAFT',"submittedAt" TIMESTAMP(3),"verifiedById" TEXT,"verifiedAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "TaxDeclaration_pkey" PRIMARY KEY("id"));
CREATE TABLE "InvestmentProof" ("id" TEXT NOT NULL,"declarationId" TEXT NOT NULL,"category" TEXT NOT NULL,"amount" DOUBLE PRECISION NOT NULL,"documentKey" TEXT NOT NULL,"status" "InvestmentProofStatus" NOT NULL DEFAULT 'PENDING',"reviewerId" TEXT,"reviewedAt" TIMESTAMP(3),"comment" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "InvestmentProof_pkey" PRIMARY KEY("id"));
CREATE TABLE "Form16Document" ("id" TEXT NOT NULL,"companyId" TEXT NOT NULL,"employeeId" TEXT NOT NULL,"financialYear" TEXT NOT NULL,"documentKey" TEXT NOT NULL,"generatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"publishedAt" TIMESTAMP(3),CONSTRAINT "Form16Document_pkey" PRIMARY KEY("id"));
CREATE TABLE "FullFinalSettlement" ("id" TEXT NOT NULL,"companyId" TEXT NOT NULL,"employeeId" TEXT NOT NULL,"lastWorkingDay" DATE NOT NULL,"status" "SettlementStatus" NOT NULL DEFAULT 'DRAFT',"unpaidSalary" DOUBLE PRECISION NOT NULL DEFAULT 0,"leaveEncashment" DOUBLE PRECISION NOT NULL DEFAULT 0,"gratuity" DOUBLE PRECISION NOT NULL DEFAULT 0,"bonus" DOUBLE PRECISION NOT NULL DEFAULT 0,"recoveries" DOUBLE PRECISION NOT NULL DEFAULT 0,"loanRecovery" DOUBLE PRECISION NOT NULL DEFAULT 0,"taxDeduction" DOUBLE PRECISION NOT NULL DEFAULT 0,"netSettlement" DOUBLE PRECISION NOT NULL DEFAULT 0,"breakdown" JSONB NOT NULL,"calculatedAt" TIMESTAMP(3),"approvedById" TEXT,"approvedAt" TIMESTAMP(3),"paidAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "FullFinalSettlement_pkey" PRIMARY KEY("id"));

CREATE UNIQUE INDEX "SalaryStructure_companyId_code_key" ON "SalaryStructure"("companyId","code"); CREATE INDEX "SalaryStructure_companyId_active_idx" ON "SalaryStructure"("companyId","active");
CREATE UNIQUE INDEX "SalaryStructureComponent_structureId_code_key" ON "SalaryStructureComponent"("structureId","code");
CREATE INDEX "EmployeeSalaryRevision_companyId_status_effectiveFrom_idx" ON "EmployeeSalaryRevision"("companyId","status","effectiveFrom"); CREATE INDEX "EmployeeSalaryRevision_employeeId_effectiveFrom_idx" ON "EmployeeSalaryRevision"("employeeId","effectiveFrom");
CREATE UNIQUE INDEX "StatutoryRuleVersion_companyId_type_stateCode_effectiveFrom_key" ON "StatutoryRuleVersion"("companyId","type","stateCode","effectiveFrom"); CREATE INDEX "StatutoryRuleVersion_companyId_type_effectiveFrom_idx" ON "StatutoryRuleVersion"("companyId","type","effectiveFrom");
CREATE INDEX "EmployeeLoan_companyId_status_idx" ON "EmployeeLoan"("companyId","status"); CREATE INDEX "EmployeeLoan_employeeId_status_idx" ON "EmployeeLoan"("employeeId","status"); CREATE INDEX "LoanRepayment_loanId_paidAt_idx" ON "LoanRepayment"("loanId","paidAt");
CREATE INDEX "PayrollAdjustment_companyId_month_idx" ON "PayrollAdjustment"("companyId","month"); CREATE INDEX "PayrollAdjustment_employeeId_month_idx" ON "PayrollAdjustment"("employeeId","month");
CREATE UNIQUE INDEX "PayrollLine_payrollRunId_employeeId_key" ON "PayrollLine"("payrollRunId","employeeId"); CREATE INDEX "PayrollLine_employeeId_idx" ON "PayrollLine"("employeeId");
CREATE UNIQUE INDEX "TaxDeclaration_employeeId_financialYear_key" ON "TaxDeclaration"("employeeId","financialYear"); CREATE INDEX "TaxDeclaration_companyId_financialYear_status_idx" ON "TaxDeclaration"("companyId","financialYear","status"); CREATE INDEX "InvestmentProof_declarationId_status_idx" ON "InvestmentProof"("declarationId","status");
CREATE UNIQUE INDEX "Form16Document_employeeId_financialYear_key" ON "Form16Document"("employeeId","financialYear"); CREATE INDEX "Form16Document_companyId_financialYear_idx" ON "Form16Document"("companyId","financialYear");
CREATE UNIQUE INDEX "FullFinalSettlement_employeeId_lastWorkingDay_key" ON "FullFinalSettlement"("employeeId","lastWorkingDay"); CREATE INDEX "FullFinalSettlement_companyId_status_idx" ON "FullFinalSettlement"("companyId","status");

ALTER TABLE "SalaryStructure" ADD CONSTRAINT "SalaryStructure_companyId_fkey" FOREIGN KEY("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "SalaryStructureComponent" ADD CONSTRAINT "SalaryStructureComponent_structureId_fkey" FOREIGN KEY("structureId") REFERENCES "SalaryStructure"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "EmployeeSalaryRevision" ADD CONSTRAINT "EmployeeSalaryRevision_companyId_fkey" FOREIGN KEY("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "EmployeeSalaryRevision" ADD CONSTRAINT "EmployeeSalaryRevision_employeeId_fkey" FOREIGN KEY("employeeId") REFERENCES "Employee"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "EmployeeSalaryRevision" ADD CONSTRAINT "EmployeeSalaryRevision_structureId_fkey" FOREIGN KEY("structureId") REFERENCES "SalaryStructure"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "StatutoryRuleVersion" ADD CONSTRAINT "StatutoryRuleVersion_companyId_fkey" FOREIGN KEY("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "EmployeeLoan" ADD CONSTRAINT "EmployeeLoan_companyId_fkey" FOREIGN KEY("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "EmployeeLoan" ADD CONSTRAINT "EmployeeLoan_employeeId_fkey" FOREIGN KEY("employeeId") REFERENCES "Employee"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "LoanRepayment" ADD CONSTRAINT "LoanRepayment_loanId_fkey" FOREIGN KEY("loanId") REFERENCES "EmployeeLoan"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "PayrollAdjustment" ADD CONSTRAINT "PayrollAdjustment_companyId_fkey" FOREIGN KEY("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "PayrollAdjustment" ADD CONSTRAINT "PayrollAdjustment_employeeId_fkey" FOREIGN KEY("employeeId") REFERENCES "Employee"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "PayrollLine" ADD CONSTRAINT "PayrollLine_payrollRunId_fkey" FOREIGN KEY("payrollRunId") REFERENCES "PayrollRun"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "TaxDeclaration" ADD CONSTRAINT "TaxDeclaration_companyId_fkey" FOREIGN KEY("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "TaxDeclaration" ADD CONSTRAINT "TaxDeclaration_employeeId_fkey" FOREIGN KEY("employeeId") REFERENCES "Employee"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "InvestmentProof" ADD CONSTRAINT "InvestmentProof_declarationId_fkey" FOREIGN KEY("declarationId") REFERENCES "TaxDeclaration"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Form16Document" ADD CONSTRAINT "Form16Document_companyId_fkey" FOREIGN KEY("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "Form16Document" ADD CONSTRAINT "Form16Document_employeeId_fkey" FOREIGN KEY("employeeId") REFERENCES "Employee"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "FullFinalSettlement" ADD CONSTRAINT "FullFinalSettlement_companyId_fkey" FOREIGN KEY("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "FullFinalSettlement" ADD CONSTRAINT "FullFinalSettlement_employeeId_fkey" FOREIGN KEY("employeeId") REFERENCES "Employee"("id") ON DELETE CASCADE ON UPDATE CASCADE;
