import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { ArrowRight, Briefcase, Plus, RefreshCw, UserPlus } from 'lucide-react';
import { api } from '../../services/api';
import type { Department, JobApplicant, JobPosting, JobStage } from '../../types';
import { useToast } from '../../context/ToastContext';

const stages: JobStage[] = ['APPLIED', 'SCREENING', 'INTERVIEW', 'OFFER', 'HIRED', 'REJECTED'];
export const RecruitmentPage: React.FC = () => {
  const toast = useToast();
  const [jobs, setJobs] = useState<JobPosting[]>([]); const [applicants, setApplicants] = useState<JobApplicant[]>([]); const [departments, setDepartments] = useState<Department[]>([]); const [busy, setBusy] = useState(false); const [tab, setTab] = useState<'pipeline'|'jobs'>('pipeline');
  const [job, setJob] = useState({ title:'', departmentId:'', location:'Remote', experienceLevel:'Any', minSalary:0, maxSalary:0, description:'', requirements:'' });
  const [candidate, setCandidate] = useState({ jobPostingId:'', fullName:'', email:'', source:'CAREERS_PAGE', experienceYears:0 });
  const load = useCallback(async () => { setBusy(true); try { const [workspace, units] = await Promise.all([api.getRecruitmentWorkspace(), api.getDepartmentsV1()]); setJobs(workspace.jobs); setApplicants(workspace.applicants); setDepartments(units); setJob(old => ({...old,departmentId:old.departmentId||units[0]?.id||''})); setCandidate(old => ({...old,jobPostingId:old.jobPostingId||workspace.jobs[0]?.id||''})); } catch(error) { toast.error('Recruitment data could not be loaded',error instanceof Error?error.message:'Unknown error'); } finally { setBusy(false); } },[toast]);
  useEffect(()=>{void load()},[load]);
  const jobNames=useMemo(()=>new Map(jobs.map(item=>[item.id,item.title])),[jobs]);
  const createJob=async(event:React.FormEvent)=>{event.preventDefault();setBusy(true);try{await api.createJobV1({title:job.title,departmentId:job.departmentId,location:job.location,employmentType:'FULL_TIME',experienceLevel:job.experienceLevel,minSalary:Number(job.minSalary),maxSalary:Number(job.maxSalary),currency:'INR',status:'OPEN',description:job.description,requirements:job.requirements.split(',').map(x=>x.trim()).filter(Boolean)});toast.success('Job opening created');setJob(old=>({...old,title:'',description:'',requirements:''}));await load()}catch(error){toast.error('Job could not be created',error instanceof Error?error.message:'Unknown error')}finally{setBusy(false)}};
  const createCandidate=async(event:React.FormEvent)=>{event.preventDefault();setBusy(true);try{await api.createApplicantV1({...candidate,experienceYears:Number(candidate.experienceYears)});toast.success('Candidate added');setCandidate(old=>({...old,fullName:'',email:''}));await load()}catch(error){toast.error('Candidate could not be added',error instanceof Error?error.message:'Unknown error')}finally{setBusy(false)}};
  const advance=async(applicant:JobApplicant)=>{const index=stages.indexOf(applicant.stage);const next=stages[Math.min(index+1,stages.length-2)];if(next===applicant.stage)return;try{await api.advanceApplicantV1(applicant.id,next);await load()}catch(error){toast.error('Stage update failed',error instanceof Error?error.message:'Unknown error')}};
  return <div className="neo-page space-y-5"><header className="flex flex-wrap justify-between gap-3 border-b border-slate-800 pb-4"><div><h1 className="text-2xl font-bold flex gap-2"><Briefcase className="text-brand-400"/>Recruitment & ATS</h1><p className="text-xs text-slate-400">Tenant-secured job requisitions, candidate sources, stage history, and hiring analytics.</p></div><button onClick={()=>void load()} className="p-2 border border-slate-700 rounded-xl"><RefreshCw className={`w-4 ${busy?'animate-spin':''}`}/></button></header><div className="flex gap-2">{(['pipeline','jobs']as const).map(value=><button key={value} onClick={()=>setTab(value)} className={`px-4 py-2 rounded-xl text-xs font-bold ${tab===value?'bg-brand-500':'bg-slate-900 border border-slate-800'}`}>{value==='pipeline'?'Candidate pipeline':'Job openings'}</button>)}</div>
  {tab==='pipeline'&&<><form onSubmit={createCandidate} className="grid md:grid-cols-6 gap-2 bg-slate-900 border border-slate-800 rounded-2xl p-4"><select required value={candidate.jobPostingId} onChange={e=>setCandidate({...candidate,jobPostingId:e.target.value})} className="input"><option value="">Job</option>{jobs.filter(x=>x.status==='OPEN').map(x=><option key={x.id} value={x.id}>{x.title}</option>)}</select><input required value={candidate.fullName} onChange={e=>setCandidate({...candidate,fullName:e.target.value})} placeholder="Candidate name" className="input"/><input required type="email" value={candidate.email} onChange={e=>setCandidate({...candidate,email:e.target.value})} placeholder="Email" className="input"/><input value={candidate.source} onChange={e=>setCandidate({...candidate,source:e.target.value})} placeholder="Source" className="input"/><input type="number" min="0" value={candidate.experienceYears} onChange={e=>setCandidate({...candidate,experienceYears:Number(e.target.value)})} placeholder="Experience" className="input"/><button disabled={busy} className="bg-brand-500 rounded-xl flex justify-center items-center gap-2"><UserPlus className="w-4"/>Add</button></form><div className="grid xl:grid-cols-6 gap-3">{stages.map(stage=><section key={stage} className="bg-slate-900 border border-slate-800 rounded-2xl p-3 min-h-72"><h2 className="text-xs font-bold mb-3">{stage.replace('_',' ')}</h2>{applicants.filter(x=>x.stage===stage).map(item=><article key={item.id} className="bg-slate-950 rounded-xl p-3 mb-2 text-xs"><strong>{item.fullName}</strong><small className="block text-slate-500">{jobNames.get(item.jobPostingId)} · {item.source||'Unspecified'}</small>{!['HIRED','REJECTED'].includes(stage)&&<button onClick={()=>void advance(item)} className="mt-2 text-brand-300 flex gap-1">Next <ArrowRight className="w-3"/></button>}</article>)}</section>)}</div></>}
  {tab==='jobs'&&<div className="grid lg:grid-cols-[360px_1fr] gap-5"><form onSubmit={createJob} className="bg-slate-900 border border-slate-800 rounded-2xl p-4 space-y-2"><h2 className="font-bold flex gap-2"><Plus className="w-4"/>Create opening</h2><input required value={job.title} onChange={e=>setJob({...job,title:e.target.value})} placeholder="Title" className="input w-full"/><select required value={job.departmentId} onChange={e=>setJob({...job,departmentId:e.target.value})} className="input w-full">{departments.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><input required value={job.location} onChange={e=>setJob({...job,location:e.target.value})} placeholder="Location" className="input w-full"/><input required value={job.experienceLevel} onChange={e=>setJob({...job,experienceLevel:e.target.value})} placeholder="Experience" className="input w-full"/><div className="grid grid-cols-2 gap-2"><input type="number" min="0" value={job.minSalary} onChange={e=>setJob({...job,minSalary:Number(e.target.value)})} className="input"/><input type="number" min="0" value={job.maxSalary} onChange={e=>setJob({...job,maxSalary:Number(e.target.value)})} className="input"/></div><textarea required value={job.description} onChange={e=>setJob({...job,description:e.target.value})} placeholder="Description" className="input w-full"/><input value={job.requirements} onChange={e=>setJob({...job,requirements:e.target.value})} placeholder="Requirements, comma separated" className="input w-full"/><button disabled={busy} className="w-full bg-brand-500 rounded-xl p-2">Create</button></form><div className="grid md:grid-cols-2 gap-3">{jobs.map(item=><article key={item.id} className="bg-slate-900 border border-slate-800 rounded-2xl p-4"><h3 className="font-bold">{item.title}</h3><p className="text-xs text-slate-400">{item.location} · {item.experienceLevel}</p><p className="text-xs mt-3">{item.description}</p><small className="text-brand-300">{item.applicantCount} applicants · {item.status}</small></article>)}</div></div>}</div>;
};
