package com.orbithr.app.core.model

import kotlinx.serialization.Serializable

@Serializable data class ApiEnvelope<T>(val data: T, val meta: ApiMeta = ApiMeta())
@Serializable data class ApiMeta(val requestId: String? = null, val page: Int? = null, val pageSize: Int? = null, val total: Int? = null, val totalPages: Int? = null)
@Serializable data class ApiErrorEnvelope(val error: ApiError, val meta: ApiMeta? = null)
@Serializable data class ApiError(val code: String, val message: String)
@Serializable data class SessionDto(val accessToken: String, val refreshToken: String, val expiresInSeconds: Int)
@Serializable data class LoginRequest(val email: String, val password: String, val deviceName: String? = null)
@Serializable data class RefreshRequest(val refreshToken: String, val deviceName: String? = null)
@Serializable data class UserDto(val id: String, val email: String, val fullName: String, val role: String, val avatarUrl: String? = null, val permissions: List<String> = emptyList())
@Serializable data class CompanyDto(val id: String, val name: String, val email: String, val logoUrl: String? = null)
@Serializable data class DepartmentDto(val id: String, val name: String, val code: String)
@Serializable data class DesignationDto(val id: String, val title: String)
@Serializable data class EmployeeDto(val id: String, val employeeCode: String, val firstName: String, val lastName: String, val email: String, val phone: String? = null, val avatarUrl: String? = null, val status: String, val workLocation: String? = null, val department: DepartmentDto? = null, val designation: DesignationDto? = null)
@Serializable data class MeDto(val user: UserDto, val company: CompanyDto, val employee: EmployeeDto? = null)
@Serializable data class AnnouncementDto(val id: String, val title: String, val content: String, val priority: String, val createdAt: String)
@Serializable data class HolidayDto(val id: String, val name: String, val date: String, val type: String)
@Serializable data class DashboardDto(val activeEmployees: Int, val presentToday: Int, val pendingLeaves: Int, val announcements: List<AnnouncementDto>, val holidays: List<HolidayDto>)
@Serializable data class AttendanceDto(val id: String, val date: String, val status: String, val clockInTime: String? = null, val clockOutTime: String? = null, val source: String)
@Serializable data class PunchRequest(val action: String, val latitude: Double? = null, val longitude: Double? = null, val deviceId: String? = null)
@Serializable data class LeaveTypeDto(val id: String, val name: String, val code: String, val daysAllowedPerYear: Int, val isPaid: Boolean, val color: String)
@Serializable data class LeaveRequestDto(val id: String, val leaveTypeId: String, val startDate: String, val endDate: String, val totalDays: Double, val reason: String, val status: String, val leaveType: LeaveTypeDto? = null)
@Serializable data class LeavesDto(val requests: List<LeaveRequestDto>, val types: List<LeaveTypeDto>)
@Serializable data class ApplyLeaveRequest(val leaveTypeId: String, val startDate: String, val endDate: String, val reason: String)
@Serializable data class PayslipDto(val id: String, val month: String, val grossSalary: Double, val totalDeductions: Double, val netSalary: Double, val status: String, val paymentDate: String? = null)
@Serializable data class ExpenseDto(val id: String, val title: String, val category: String, val amount: Double, val currency: String, val expenseDate: String, val status: String, val notes: String? = null)
@Serializable data class SubmitExpenseRequest(val title: String, val category: String, val amount: Double, val expenseDate: String, val notes: String? = null)
@Serializable data class OnboardEmployeeRequest(val employeeCode: String, val firstName: String, val lastName: String, val email: String, val departmentId: String, val designationId: String, val dateOfJoining: String, val employmentType: String = "FULL_TIME", val workLocation: String? = null, val phone: String? = null)
@Serializable data class OnboardingDto(val employee: EmployeeDto, val emailDelivery: EmailDeliveryDto)
@Serializable data class EmailDeliveryDto(val id: String, val status: String)
