package com.orbithr.app.ui

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.orbithr.app.core.data.OrbitRepository
import com.orbithr.app.core.data.userMessage
import com.orbithr.app.core.model.*
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch
import javax.inject.Inject

data class LoadState<T>(val data: T? = null, val loading: Boolean = true, val error: String? = null)
@HiltViewModel class HomeViewModel @Inject constructor(private val repo: OrbitRepository): ViewModel() { private val _state = MutableStateFlow(LoadState<DashboardDto>()); val state = _state.asStateFlow(); init { refresh() }; fun refresh() = viewModelScope.launch { _state.value = _state.value.copy(loading=true,error=null); runCatching { repo.dashboard() }.onSuccess { _state.value=LoadState(it,false) }.onFailure { _state.value=LoadState(error=it.userMessage(),loading=false) } } }
@HiltViewModel class AttendanceViewModel @Inject constructor(private val repo: OrbitRepository): ViewModel() { private val _state=MutableStateFlow(LoadState<List<AttendanceDto>>()); val state=_state.asStateFlow(); init{refresh()}; fun refresh()=viewModelScope.launch{runCatching{repo.attendance()}.onSuccess{_state.value=LoadState(it,false)}.onFailure{_state.value=LoadState(error=it.userMessage(),loading=false)}}; fun punch(action:String)=viewModelScope.launch{_state.value=_state.value.copy(loading=true,error=null);runCatching{repo.punch(action)}.onSuccess{refresh()}.onFailure{_state.value=_state.value.copy(loading=false,error=it.userMessage())}} }
@HiltViewModel class LeaveViewModel @Inject constructor(private val repo: OrbitRepository):ViewModel(){private val _state=MutableStateFlow(LoadState<LeavesDto>());val state=_state.asStateFlow();init{refresh()};fun refresh()=viewModelScope.launch{runCatching{repo.leaves()}.onSuccess{_state.value=LoadState(it,false)}.onFailure{_state.value=LoadState(error=it.userMessage(),loading=false)}};fun apply(body:ApplyLeaveRequest)=viewModelScope.launch{_state.value=_state.value.copy(loading=true,error=null);runCatching{repo.applyLeave(body)}.onSuccess{refresh()}.onFailure{_state.value=_state.value.copy(loading=false,error=it.userMessage())}}}
@HiltViewModel class PayViewModel @Inject constructor(private val repo:OrbitRepository):ViewModel(){private val _state=MutableStateFlow(LoadState<List<PayslipDto>>());val state=_state.asStateFlow();init{viewModelScope.launch{runCatching{repo.payslips()}.onSuccess{_state.value=LoadState(it,false)}.onFailure{_state.value=LoadState(error=it.userMessage(),loading=false)}}}}
@HiltViewModel class ExpenseViewModel @Inject constructor(private val repo:OrbitRepository):ViewModel(){private val _state=MutableStateFlow(LoadState<List<ExpenseDto>>());val state=_state.asStateFlow();init{refresh()};fun refresh()=viewModelScope.launch{runCatching{repo.expenses()}.onSuccess{_state.value=LoadState(it,false)}.onFailure{_state.value=LoadState(error=it.userMessage(),loading=false)}};fun submit(body:SubmitExpenseRequest)=viewModelScope.launch{_state.value=_state.value.copy(loading=true);runCatching{repo.submitExpense(body)}.onSuccess{refresh()}.onFailure{_state.value=_state.value.copy(loading=false,error=it.userMessage())}}}
@HiltViewModel class EmployeeViewModel @Inject constructor(private val repo:OrbitRepository):ViewModel(){private val _state=MutableStateFlow(LoadState<List<EmployeeDto>>());val state=_state.asStateFlow();fun search(value:String?=null)=viewModelScope.launch{_state.value=_state.value.copy(loading=true);runCatching{repo.employees(1,value)}.onSuccess{_state.value=LoadState(it,false)}.onFailure{_state.value=LoadState(error=it.userMessage(),loading=false)}};init{search()};fun onboard(body:OnboardEmployeeRequest)=viewModelScope.launch{_state.value=_state.value.copy(loading=true);runCatching{repo.onboard(body)}.onSuccess{search()}.onFailure{_state.value=_state.value.copy(loading=false,error=it.userMessage())}}}
