import { Router, type Request, type RequestHandler, type Response } from 'express';
import type { PrismaClient } from '@prisma/client';
import { z } from 'zod';
import { evaluateAttendance } from './attendanceEngine.js';
import { startConfiguredWorkflow } from './workflows.js';

type AttendanceRequest = Request & { auth?: { id: string; companyId: string; role: string; employeeId?: string; permissions: string[] }; requestId?: string };
const id=z.string().uuid(); const day=(value:Date)=>new Date(Date.UTC(value.getUTCFullYear(),value.getUTCMonth(),value.getUTCDate()));
export function createAttendancePolicyRouter(prisma:PrismaClient,authenticate:RequestHandler){
 const router=Router(); const ok=(res:Response,data:unknown,status=200)=>res.status(status).json({data,meta:{requestId:(res.req as AttendanceRequest).requestId}}); const fail=(res:Response,status:number,code:string,message:string)=>res.status(status).json({error:{code,message}}); const permit=(p:string):RequestHandler=>(req:AttendanceRequest,res,next)=>req.auth?.permissions.includes(p)?next():fail(res,403,'FORBIDDEN','You do not have permission to perform this action.');
 router.use('/attendance',authenticate);
 router.get('/attendance/config',permit('attendance.manage'),async(req:AttendanceRequest,res,next)=>{try{const companyId=req.auth!.companyId;const [shifts,policies,assignments,locks]=await prisma.$transaction([prisma.shiftTemplate.findMany({where:{companyId},orderBy:{name:'asc'}}),prisma.attendancePolicy.findMany({where:{companyId},include:{shiftTemplate:true},orderBy:{effectiveFrom:'desc'}}),prisma.shiftAssignment.findMany({where:{companyId},include:{employee:{select:{id:true,firstName:true,lastName:true,employeeCode:true}},shiftTemplate:true},orderBy:{startsOn:'desc'}}),prisma.attendancePeriodLock.findMany({where:{companyId},orderBy:{periodStart:'desc'}})]);return ok(res,{shifts,policies,assignments,locks})}catch(e){next(e)}});
 router.post('/attendance/shifts',permit('attendance.manage'),async(req:AttendanceRequest,res,next)=>{try{const body=z.object({name:z.string().trim().min(2).max(120),code:z.string().trim().min(2).max(40).transform(v=>v.toUpperCase()),type:z.enum(['FIXED','FLEXIBLE','NIGHT','ROTATIONAL']).default('FIXED'),startMinute:z.number().int().min(0).max(1439),endMinute:z.number().int().min(0).max(1439),breakMinutes:z.number().int().min(0).max(600).default(0),crossesMidnight:z.boolean().default(false),weeklyOffDays:z.array(z.number().int().min(0).max(6)).default([0])}).parse(req.body);return ok(res,await prisma.shiftTemplate.create({data:{...body,companyId:req.auth!.companyId}}),201)}catch(e){next(e)}});
 router.post('/attendance/policies',permit('attendance.manage'),async(req:AttendanceRequest,res,next)=>{try{const body=z.object({name:z.string().trim().min(2).max(120),shiftTemplateId:id.optional(),graceInMinutes:z.number().int().min(0).max(240).default(0),graceOutMinutes:z.number().int().min(0).max(240).default(0),halfDayAfterMinutes:z.number().int().min(1).max(1440).default(240),fullDayMinutes:z.number().int().min(1).max(1440).default(480),overtimeAfterMinutes:z.number().int().min(1).max(1440).default(480),missingPunchAction:z.enum(['FLAG','ABSENT','HALF_DAY']).default('FLAG'),allowRemote:z.boolean().default(false),requireGeofence:z.boolean().default(true),requireFace:z.boolean().default(true),effectiveFrom:z.coerce.date(),effectiveTo:z.coerce.date().optional()}).parse(req.body);if(body.shiftTemplateId&&!await prisma.shiftTemplate.findFirst({where:{id:body.shiftTemplateId,companyId:req.auth!.companyId}}))return fail(res,400,'SHIFT_INVALID','Shift is not part of this company.');return ok(res,await prisma.attendancePolicy.create({data:{...body,companyId:req.auth!.companyId}}),201)}catch(e){next(e)}});
 router.post('/attendance/assignments',permit('attendance.manage'),async(req:AttendanceRequest,res,next)=>{try{const body=z.object({employeeId:id,shiftTemplateId:id,startsOn:z.coerce.date(),endsOn:z.coerce.date().optional()}).parse(req.body);const companyId=req.auth!.companyId;const [employee,shift]=await Promise.all([prisma.employee.findFirst({where:{id:body.employeeId,companyId}}),prisma.shiftTemplate.findFirst({where:{id:body.shiftTemplateId,companyId}})]);if(!employee||!shift)return fail(res,400,'ASSIGNMENT_INVALID','Employee or shift is not part of this company.');return ok(res,await prisma.shiftAssignment.create({data:{...body,companyId}}),201)}catch(e){next(e)}});
 router.post('/attendance/locks',permit('attendance.manage'),async(req:AttendanceRequest,res,next)=>{try{const body=z.object({periodStart:z.coerce.date(),periodEnd:z.coerce.date(),reason:z.string().trim().max(300).optional()}).refine(v=>v.periodEnd>=v.periodStart,'Period end must not precede start.').parse(req.body);return ok(res,await prisma.attendancePeriodLock.create({data:{companyId:req.auth!.companyId,periodStart:day(body.periodStart),periodEnd:day(body.periodEnd),reason:body.reason,lockedById:req.auth!.id}}),201)}catch(e){next(e)}});
 router.post('/attendance/evaluate/:employeeId/:date',permit('attendance.manage'),async(req:AttendanceRequest,res,next)=>{try{const companyId=req.auth!.companyId,date=day(z.coerce.date().parse(req.params.date));const employee=await prisma.employee.findFirst({where:{id:String(req.params.employeeId),companyId}});if(!employee)return fail(res,404,'EMPLOYEE_NOT_FOUND','Employee was not found.');const record=await prisma.attendanceRecord.findUnique({where:{employeeId_date:{employeeId:employee.id,date}}});if(!record)return fail(res,404,'ATTENDANCE_NOT_FOUND','Attendance record was not found.');const assignment=await prisma.shiftAssignment.findFirst({where:{companyId,employeeId:employee.id,startsOn:{lte:date},OR:[{endsOn:null},{endsOn:{gte:date}}]},include:{shiftTemplate:{include:{policies:{where:{active:true,effectiveFrom:{lte:date},OR:[{effectiveTo:null},{effectiveTo:{gte:date}}]},orderBy:{effectiveFrom:'desc'},take:1}}}},orderBy:{startsOn:'desc'}});if(!assignment||!assignment.shiftTemplate.policies[0])return fail(res,409,'ATTENDANCE_POLICY_MISSING','No effective shift policy is assigned.');const shift=assignment.shiftTemplate,policy=shift.policies[0];const breaks=await prisma.breakSession.findMany({where:{employeeId:employee.id,date}});const breakMinutes=breaks.reduce((sum,b)=>sum+(b.endedAt?Math.max(0,Math.round((b.endedAt.getTime()-b.startedAt.getTime())/60000)):0),0);const result=evaluateAttendance({clockIn:record.clockInTime,clockOut:record.clockOutTime,breakMinutes,policy:{startMinute:shift.startMinute,endMinute:shift.endMinute,crossesMidnight:shift.crossesMidnight,graceInMinutes:policy.graceInMinutes,graceOutMinutes:policy.graceOutMinutes,halfDayAfterMinutes:policy.halfDayAfterMinutes,fullDayMinutes:policy.fullDayMinutes,overtimeAfterMinutes:policy.overtimeAfterMinutes}});const evaluation=await prisma.$transaction(async tx=>{await tx.attendanceRecord.update({where:{id:record.id},data:{status:result.status}});return tx.attendanceEvaluation.upsert({where:{attendanceRecordId:record.id},create:{attendanceRecordId:record.id,shiftTemplateId:shift.id,policyId:policy.id,...result,explanation:result.explanation},update:{shiftTemplateId:shift.id,policyId:policy.id,...result,explanation:result.explanation,evaluatedAt:new Date()}})});return ok(res,evaluation)}catch(e){next(e)}});
 router.use('/me/attendance',authenticate);
 router.get('/me/attendance/requests',async(req:AttendanceRequest,res,next)=>{try{if(!req.auth!.employeeId)return fail(res,409,'EMPLOYEE_NOT_LINKED','No employee profile is linked.');return ok(res,await prisma.attendanceRequest.findMany({where:{companyId:req.auth!.companyId,employeeId:req.auth!.employeeId},orderBy:{createdAt:'desc'}}))}catch(e){next(e)}});
 router.post('/me/attendance/requests',async(req:AttendanceRequest,res,next)=>{try{if(!req.auth!.employeeId)return fail(res,409,'EMPLOYEE_NOT_LINKED','No employee profile is linked.');const body=z.object({type:z.enum(['REGULARIZATION','WFH','ON_DUTY','BUSINESS_TRAVEL','OVERTIME']),startDate:z.coerce.date(),endDate:z.coerce.date(),requestedClockIn:z.coerce.date().optional(),requestedClockOut:z.coerce.date().optional(),reason:z.string().trim().min(3).max(1000)}).refine(v=>v.endDate>=v.startDate,'End date must not precede start.').parse(req.body);const module=body.type==='REGULARIZATION'?'ATTENDANCE_CORRECTION':body.type;const result=await prisma.$transaction(async tx=>{const request=await tx.attendanceRequest.create({data:{...body,companyId:req.auth!.companyId,employeeId:req.auth!.employeeId!}});const workflow=await startConfiguredWorkflow(tx,{companyId:req.auth!.companyId,requesterUserId:req.auth!.id,module,subjectType:'AttendanceRequest',subjectId:request.id,title:`${body.type.replaceAll('_',' ')} request`,summary:body.reason,payload:{startDate:body.startDate.toISOString(),endDate:body.endDate.toISOString()}});if(workflow)await tx.attendanceRequest.update({where:{id:request.id},data:{workflowInstanceId:workflow.id}});return{...request,workflowInstanceId:workflow?.id}});return ok(res,result,201)}catch(e){next(e)}});
 router.post('/me/attendance/breaks/start',async(req:AttendanceRequest,res,next)=>{try{if(!req.auth!.employeeId)return fail(res,409,'EMPLOYEE_NOT_LINKED','No employee profile is linked.');const date=day(new Date());if(await prisma.breakSession.findFirst({where:{employeeId:req.auth!.employeeId,date,endedAt:null}}))return fail(res,409,'BREAK_ALREADY_ACTIVE','A break is already active.');return ok(res,await prisma.breakSession.create({data:{employeeId:req.auth!.employeeId,date,startedAt:new Date()}}),201)}catch(e){next(e)}});
 router.post('/me/attendance/breaks/end',async(req:AttendanceRequest,res,next)=>{try{if(!req.auth!.employeeId)return fail(res,409,'EMPLOYEE_NOT_LINKED','No employee profile is linked.');const active=await prisma.breakSession.findFirst({where:{employeeId:req.auth!.employeeId,endedAt:null},orderBy:{startedAt:'desc'}});if(!active)return fail(res,409,'NO_ACTIVE_BREAK','No active break exists.');return ok(res,await prisma.breakSession.update({where:{id:active.id},data:{endedAt:new Date()}}))}catch(e){next(e)}});
 return router;
}
