import crypto from 'node:crypto';

const alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';
function key() { const raw = process.env.MFA_ENCRYPTION_KEY; if (!raw) throw Object.assign(new Error('MFA encryption is not configured.'), { status: 503, code: 'MFA_NOT_CONFIGURED' }); const value = Buffer.from(raw, 'base64'); if (value.length !== 32) throw Object.assign(new Error('MFA_ENCRYPTION_KEY must be a base64-encoded 32-byte key.'), { status: 503, code: 'MFA_NOT_CONFIGURED' }); return value; }
export function newMfaSecret() { const bytes = crypto.randomBytes(20); let bits = ''; for (const b of bytes) bits += b.toString(2).padStart(8, '0'); let result = ''; for (let i = 0; i < bits.length; i += 5) result += alphabet[parseInt(bits.slice(i, i + 5).padEnd(5, '0'), 2)]; return result; }
function decodeBase32(value: string) { let bits = ''; for (const c of value.replace(/=+$/,'').toUpperCase()) { const n = alphabet.indexOf(c); if (n < 0) throw new Error('Invalid base32 secret'); bits += n.toString(2).padStart(5,'0'); } const out:number[]=[]; for(let i=0;i+8<=bits.length;i+=8)out.push(parseInt(bits.slice(i,i+8),2)); return Buffer.from(out); }
export function encryptMfaSecret(secret:string){const iv=crypto.randomBytes(12),cipher=crypto.createCipheriv('aes-256-gcm',key(),iv),encrypted=Buffer.concat([cipher.update(secret,'utf8'),cipher.final()]);return Buffer.concat([iv,cipher.getAuthTag(),encrypted]).toString('base64')}
export function decryptMfaSecret(value:string){const packed=Buffer.from(value,'base64'),iv=packed.subarray(0,12),tag=packed.subarray(12,28),decipher=crypto.createDecipheriv('aes-256-gcm',key(),iv);decipher.setAuthTag(tag);return Buffer.concat([decipher.update(packed.subarray(28)),decipher.final()]).toString('utf8')}
function codeAt(secret:string,counter:number){const buffer=Buffer.alloc(8);buffer.writeBigUInt64BE(BigInt(counter));const hash=crypto.createHmac('sha1',decodeBase32(secret)).update(buffer).digest(),offset=hash[19]&15,value=((hash[offset]&127)<<24)|((hash[offset+1]&255)<<16)|((hash[offset+2]&255)<<8)|(hash[offset+3]&255);return String(value%1_000_000).padStart(6,'0')}
export function verifyMfaCode(encrypted:string,code:string,now=Date.now()){const secret=decryptMfaSecret(encrypted),counter=Math.floor(now/30_000);return[-1,0,1].some(delta=>{const expected=codeAt(secret,counter+delta);return code.length===expected.length&&crypto.timingSafeEqual(Buffer.from(code),Buffer.from(expected))})}
