export type SalaryComponentInput={code:string;name:string;kind:'EARNING'|'DEDUCTION'|'EMPLOYER_CONTRIBUTION'|'REIMBURSEMENT';method:'FIXED'|'PERCENT_BASIC'|'PERCENT_GROSS';value:number;proratable:boolean;taxable:boolean};
export type StatutoryRuleInput={type:'PF'|'ESI'|'PROFESSIONAL_TAX'|'TDS'|'LWF';configuration:Record<string,unknown>};
export type PayrollCalculationInput={components:SalaryComponentInput[];overrides?:Record<string,number>;adjustments?:Array<{code:string;name:string;kind:SalaryComponentInput['kind'];amount:number}>;rules?:StatutoryRuleInput[];workingDays:number;payableDays:number;loanInstallment?:number};
const money=(n:number)=>Math.round((n+Number.EPSILON)*100)/100;const numeric=(v:unknown,fallback=0)=>typeof v==='number'&&Number.isFinite(v)?v:fallback;
export function calculatePayroll(input:PayrollCalculationInput){
 const ratio=input.workingDays>0?Math.max(0,Math.min(1,input.payableDays/input.workingDays)):0;const values:Record<string,number>={};const nominal:Record<string,number>={};const trace:string[]=[];const ordered=[...input.components].sort((a,b)=>(a.method==='FIXED'?0:a.method==='PERCENT_BASIC'?1:2)-(b.method==='FIXED'?0:b.method==='PERCENT_BASIC'?1:2));
 for(const component of ordered){let amount=input.overrides?.[component.code]??component.value;if(input.overrides?.[component.code]==null){if(component.method==='PERCENT_BASIC')amount=(nominal.BASIC||0)*component.value/100;if(component.method==='PERCENT_GROSS')amount=Object.entries(nominal).filter(([code])=>input.components.find(x=>x.code===code)?.kind==='EARNING').reduce((sum,[,v])=>sum+v,0)*component.value/100}nominal[component.code]=amount;if(component.proratable)amount*=ratio;values[component.code]=money(amount);trace.push(`${component.code}=${values[component.code]} (${component.method}${component.proratable?`, ratio ${ratio.toFixed(6)}`:''})`)}
 for(const adjustment of input.adjustments||[]){values[adjustment.code]=money((values[adjustment.code]||0)+adjustment.amount);trace.push(`${adjustment.code} adjustment=${money(adjustment.amount)}`)}
 const kindTotal=(kind:SalaryComponentInput['kind'])=>money(Object.entries(values).filter(([code])=>(input.components.find(x=>x.code===code)?.kind||input.adjustments?.find(x=>x.code===code)?.kind)===kind).reduce((s,[,v])=>s+v,0));let gross=kindTotal('EARNING');let deductions=kindTotal('DEDUCTION');let employer=kindTotal('EMPLOYER_CONTRIBUTION');let reimbursements=kindTotal('REIMBURSEMENT');
 for(const rule of input.rules||[]){const c=rule.configuration;if(rule.type==='PF'){const baseCodes=Array.isArray(c.baseCodes)?c.baseCodes.map(String):['BASIC'];let base=baseCodes.reduce((s,code)=>s+(values[code]||0),0);const ceiling=numeric(c.wageCeiling);if(ceiling>0)base=Math.min(base,ceiling);const employee=money(base*numeric(c.employeeRate)/100),company=money(base*numeric(c.employerRate)/100);deductions+=employee;employer+=company;values.PF_EMPLOYEE=employee;values.PF_EMPLOYER=company;trace.push(`PF base=${money(base)}, employee=${employee}, employer=${company}`)}
 if(rule.type==='ESI'){const ceiling=numeric(c.grossCeiling);if(!ceiling||gross<=ceiling){const employee=money(gross*numeric(c.employeeRate)/100),company=money(gross*numeric(c.employerRate)/100);deductions+=employee;employer+=company;values.ESI_EMPLOYEE=employee;values.ESI_EMPLOYER=company;trace.push(`ESI gross=${gross}, employee=${employee}, employer=${company}`)}}
 if(rule.type==='PROFESSIONAL_TAX'){const slabs=Array.isArray(c.slabs)?c.slabs as Array<Record<string,unknown>>:[];const slab=slabs.find(x=>gross>=numeric(x.min)&&(!numeric(x.max)||gross<=numeric(x.max)));const amount=money(numeric(slab?.amount));deductions+=amount;values.PROFESSIONAL_TAX=amount;trace.push(`Professional tax=${amount}`)}
 if(rule.type==='LWF'){const employee=money(numeric(c.employeeAmount)),company=money(numeric(c.employerAmount));deductions+=employee;employer+=company;values.LWF_EMPLOYEE=employee;values.LWF_EMPLOYER=company;trace.push(`LWF employee=${employee}, employer=${company}`)}
 if(rule.type==='TDS'){const monthly=money(numeric(c.monthlyAmount));deductions+=monthly;values.TDS=monthly;trace.push(`TDS configured monthly amount=${monthly}`)}}
 const loan=money(Math.max(0,input.loanInstallment||0));deductions+=loan;if(loan){values.LOAN_REPAYMENT=loan;trace.push(`Loan repayment=${loan}`)}gross=money(gross);deductions=money(deductions);employer=money(employer);reimbursements=money(reimbursements);return{workingDays:input.workingDays,payableDays:input.payableDays,unpaidDays:money(Math.max(0,input.workingDays-input.payableDays)),grossEarnings:gross,employeeDeductions:deductions,employerContributions:employer,reimbursements,netPay:money(Math.max(0,gross-deductions+reimbursements)),breakdown:values,calculationTrace:trace};
}
