import { Router, type Request, type RequestHandler, type Response } from 'express';
import type { PerformanceReviewStatus, PrismaClient } from '@prisma/client';
import { z } from 'zod';
import { employeeWhere } from './governance.js';

type Req = Request & { auth?: { id:string; companyId:string; role:string; employeeId?:string; permissions:string[]; accessScopes?:Array<{scope:string;scopeEntityId?:string|null;permissions:string[]}> }; requestId?:string };
export function reviewTransition(current:string,action:string):PerformanceReviewStatus {
  const allowed:Record<string,string[]>={DRAFT:['SAVE','SUBMIT'],SUBMITTED:['MANAGER_REVIEW'],MANAGER_REVIEWED:['HR_REVIEW'],HR_REVIEWED:['ACKNOWLEDGE'],ACKNOWLEDGED:[]};
  if(!allowed[current]?.includes(action)) throw Object.assign(new Error(`Action ${action} is not allowed from ${current}.`),{status:409,code:'REVIEW_TRANSITION_INVALID'});
  return action==='SUBMIT'?'SUBMITTED':action==='MANAGER_REVIEW'?'MANAGER_REVIEWED':action==='HR_REVIEW'?'HR_REVIEWED':action==='ACKNOWLEDGE'?'ACKNOWLEDGED':current as PerformanceReviewStatus;
}
export function createPerformanceRouter(prisma:PrismaClient,authenticate:RequestHandler){
  const router=Router();
  const ok=(res:Response,data:unknown,status=200)=>res.status(status).json({data,meta:{requestId:(res.req as Req).requestId}});
  const fail=(res:Response,status:number,code:string,message:string)=>res.status(status).json({error:{code,message}});
  router.use('/performance-engine',authenticate);
  router.get('/performance-engine',async(req:Req,res,next)=>{try{const auth=req.auth!;const employeeIds=(await prisma.employee.findMany({where:employeeWhere(auth),select:{id:true}})).map(item=>item.id);const[cycles,reviews]=await prisma.$transaction([prisma.performanceCycle.findMany({where:{companyId:auth.companyId},orderBy:{startsAt:'desc'}}),prisma.performanceReview.findMany({where:{companyId:auth.companyId,OR:[{employeeId:{in:employeeIds}},{reviewerId:auth.id}]},include:{cycle:true,employee:{select:{employeeCode:true,firstName:true,lastName:true}}},orderBy:{createdAt:'desc'}})]);return ok(res,{cycles,reviews})}catch(error){next(error)}});
  router.post('/performance-engine/cycles',async(req:Req,res,next)=>{try{if(!req.auth!.permissions.includes('performance.manage'))return fail(res,403,'FORBIDDEN','Performance management permission is required.');const body=z.object({name:z.string().trim().min(2).max(120),startsAt:z.coerce.date(),endsAt:z.coerce.date(),status:z.enum(['DRAFT','ACTIVE','REVIEW','CLOSED']).default('DRAFT')}).refine(value=>value.endsAt>value.startsAt,'Cycle end must follow start.').parse(req.body);return ok(res,await prisma.performanceCycle.create({data:{...body,companyId:req.auth!.companyId}}),201)}catch(error){next(error)}});
  router.post('/performance-engine/reviews',async(req:Req,res,next)=>{try{if(!req.auth!.permissions.includes('performance.manage'))return fail(res,403,'FORBIDDEN','Performance management permission is required.');const body=z.object({cycleId:z.string().uuid(),employeeId:z.string().uuid(),reviewerId:z.string().uuid()}).parse(req.body),companyId=req.auth!.companyId;const[cycle,employee,reviewer]=await Promise.all([prisma.performanceCycle.findFirst({where:{id:body.cycleId,companyId}}),prisma.employee.findFirst({where:{id:body.employeeId,companyId}}),prisma.user.findFirst({where:{id:body.reviewerId,companyId}})]);if(!cycle||!employee||!reviewer)return fail(res,400,'PERFORMANCE_ASSIGNMENT_INVALID','Cycle, employee, or reviewer is invalid.');return ok(res,await prisma.performanceReview.create({data:{...body,companyId}}),201)}catch(error){next(error)}});
  router.patch('/performance-engine/reviews/:id',async(req:Req,res,next)=>{try{const body=z.object({overallRating:z.number().min(1).max(5).optional(),goalRating:z.number().min(1).max(5).optional(),competencyRating:z.number().min(1).max(5).optional(),strengths:z.string().max(4000).optional(),growthAreas:z.string().max(4000).optional(),summary:z.string().max(4000).optional(),action:z.enum(['SAVE','SUBMIT','MANAGER_REVIEW','HR_REVIEW','ACKNOWLEDGE'])}).parse(req.body);const review=await prisma.performanceReview.findFirst({where:{id:String(req.params.id),companyId:req.auth!.companyId}});if(!review)return fail(res,404,'REVIEW_NOT_FOUND','Performance review was not found.');const self=review.employeeId===req.auth!.employeeId,reviewer=review.reviewerId===req.auth!.id,manager=req.auth!.permissions.includes('performance.review'),admin=req.auth!.permissions.includes('performance.manage');if(body.action==='ACKNOWLEDGE'&&!self)return fail(res,403,'FORBIDDEN','Only the employee can acknowledge this review.');if(body.action!=='ACKNOWLEDGE'&&!reviewer&&!manager&&!admin)return fail(res,403,'FORBIDDEN','You cannot edit this review.');const status=reviewTransition(review.status,body.action);return ok(res,await prisma.performanceReview.update({where:{id:review.id},data:{overallRating:body.overallRating,goalRating:body.goalRating,competencyRating:body.competencyRating,strengths:body.strengths,growthAreas:body.growthAreas,summary:body.summary,status,submittedAt:body.action==='SUBMIT'?new Date():undefined,reviewedAt:['MANAGER_REVIEW','HR_REVIEW'].includes(body.action)?new Date():undefined,acknowledgedAt:body.action==='ACKNOWLEDGE'?new Date():undefined}}))}catch(error){next(error)}});
  return router;
}
