import { Router, type Request, type RequestHandler, type Response } from 'express';
import type { PrismaClient } from '@prisma/client';
import { z } from 'zod';

type Req = Request & { auth?: { id: string; companyId: string; role: string; permissions: string[] }; requestId?: string };
const stages = ['APPLIED', 'SCREENING', 'INTERVIEW', 'OFFER', 'HIRED', 'REJECTED'] as const;
export function createRecruitmentRouter(prisma: PrismaClient, authenticate: RequestHandler) {
  const router = Router();
  const ok = (res: Response, data: unknown, status = 200) => res.status(status).json({ data, meta: { requestId: (res.req as Req).requestId } });
  const fail = (res: Response, status: number, code: string, message: string) => res.status(status).json({ error: { code, message } });
  const permit: RequestHandler = (req: Req, res, next) => req.auth?.permissions.includes('recruitment.manage') ? next() : fail(res, 403, 'FORBIDDEN', 'Recruitment management permission is required.');
  const audit = (req: Req, action: string, details: string) => prisma.auditLog.create({ data: { companyId: req.auth!.companyId, userId: req.auth!.id, userName: req.auth!.id, userRole: req.auth!.role, action, category: 'RECRUITMENT', details, ipAddress: req.ip || 'unknown' } });
  router.use('/recruitment', authenticate, permit);
  router.get('/recruitment', async (req: Req, res, next) => { try { const [jobs, applicants] = await prisma.$transaction([prisma.jobPosting.findMany({ where: { companyId: req.auth!.companyId }, include: { department: { select: { id: true, name: true } } }, orderBy: { postedAt: 'desc' } }), prisma.jobApplicant.findMany({ where: { companyId: req.auth!.companyId }, include: { jobPosting: { select: { id: true, title: true } } }, orderBy: { appliedAt: 'desc' } })]); return ok(res, { jobs, applicants }); } catch (error) { next(error); } });
  router.post('/recruitment/jobs', async (req: Req, res, next) => { try { const body = z.object({ title: z.string().trim().min(2).max(160), departmentId: z.string().uuid(), location: z.string().trim().min(2).max(160), employmentType: z.enum(['FULL_TIME', 'PART_TIME', 'CONTRACT', 'INTERN', 'CONSULTANT']).default('FULL_TIME'), experienceLevel: z.string().trim().min(1).max(100), minSalary: z.number().min(0), maxSalary: z.number().min(0), currency: z.string().length(3).default('INR'), status: z.enum(['OPEN', 'CLOSED', 'DRAFT']).default('OPEN'), description: z.string().trim().min(3).max(20_000), requirements: z.array(z.string().trim().min(1).max(200)).max(100).default([]) }).refine(value => value.maxSalary >= value.minSalary, { path: ['maxSalary'], message: 'Maximum salary must not be below minimum salary.' }).parse(req.body); if (!await prisma.department.findFirst({ where: { id: body.departmentId, companyId: req.auth!.companyId } })) return fail(res, 400, 'DEPARTMENT_INVALID', 'Department is not part of this company.'); const job = await prisma.jobPosting.create({ data: { ...body, companyId: req.auth!.companyId } }); await audit(req, 'CREATE_JOB_POSTING', `Job ${job.id} (${job.title}) created.`); return ok(res, job, 201); } catch (error) { next(error); } });
  router.post('/recruitment/applicants', async (req: Req, res, next) => { try { const body = z.object({ jobPostingId: z.string().uuid(), fullName: z.string().trim().min(2).max(160), email: z.string().email(), phone: z.string().max(30).optional(), currentCompany: z.string().max(160).optional(), experienceYears: z.number().min(0).max(80).default(0), rating: z.number().int().min(1).max(5).default(3), notes: z.string().max(5000).optional(), source: z.string().trim().max(100).optional() }).parse(req.body); const job = await prisma.jobPosting.findFirst({ where: { id: body.jobPostingId, companyId: req.auth!.companyId } }); if (!job) return fail(res, 404, 'JOB_NOT_FOUND', 'Job posting was not found.'); const applicant = await prisma.$transaction(async tx => { const created = await tx.jobApplicant.create({ data: { ...body, companyId: req.auth!.companyId } }); await tx.jobPosting.update({ where: { id: job.id }, data: { applicantCount: { increment: 1 } } }); return created; }); await audit(req, 'CREATE_JOB_APPLICANT', `Candidate ${applicant.id} added to ${job.title}.`); return ok(res, applicant, 201); } catch (error) { next(error); } });
  router.patch('/recruitment/applicants/:id/stage', async (req: Req, res, next) => { try { const body = z.object({ stage: z.enum(stages), rating: z.number().int().min(1).max(5).optional(), notes: z.string().max(5000).optional() }).parse(req.body); const applicant = await prisma.jobApplicant.findFirst({ where: { id: String(req.params.id), companyId: req.auth!.companyId } }); if (!applicant) return fail(res, 404, 'APPLICANT_NOT_FOUND', 'Applicant was not found.'); const updated = await prisma.jobApplicant.update({ where: { id: applicant.id }, data: { stage: body.stage, rating: body.rating, notes: body.notes, stageUpdatedAt: new Date(), hiredAt: body.stage === 'HIRED' ? applicant.hiredAt || new Date() : body.stage === 'REJECTED' ? null : applicant.hiredAt } }); await audit(req, 'ADVANCE_CANDIDATE', `Candidate ${applicant.id} moved from ${applicant.stage} to ${body.stage}.`); return ok(res, updated); } catch (error) { next(error); } });
  return router;
}
