import { Router, type Request, type RequestHandler, type Response } from 'express';
import type { PrismaClient } from '@prisma/client';
import { z } from 'zod';
import { zipSync, strToU8 } from 'fflate';
import { jsPDF } from 'jspdf';
import { employeeWhere } from './governance.js';

type Auth={id:string;companyId:string;role:string;employeeId?:string;permissions:string[];accessScopes?:Array<{scope:string;scopeEntityId?:string|null;permissions:string[]}>};type Req=Request&{auth?:Auth;requestId?:string};
export const reportDefinitions=[
  ['WORKFORCE_HEADCOUNT','Headcount register','employee.read.all'],['WORKFORCE_ATTRITION','Attrition and exits','employee.read.all'],['WORKFORCE_NEW_HIRES','New hires','employee.read.all'],['WORKFORCE_DEPARTMENTS','Department distribution','employee.read.all'],['WORKFORCE_EMPLOYMENT_TYPES','Employment type distribution','employee.read.all'],
  ['ATTENDANCE_SUMMARY','Attendance summary','attendance.read.team'],['ATTENDANCE_LATE','Late arrivals','attendance.read.team'],['ATTENDANCE_ABSENCE','Absence report','attendance.read.team'],['ATTENDANCE_OVERTIME','Overtime report','attendance.read.team'],['ATTENDANCE_SHIFTS','Shift assignments','attendance.read.team'],
  ['LEAVE_UTILIZATION','Leave utilization','leave.review'],['LEAVE_TRENDS','Leave trends','leave.review'],['LEAVE_BALANCES','Leave balances','leave.review'],
  ['PAYROLL_SUMMARY','Payroll summary','payroll.manage'],['PAYROLL_DEPARTMENT_COST','Department salary cost','payroll.manage'],['PAYROLL_STATUTORY','PF, ESI and tax summary','payroll.manage'],['PAYROLL_TREND','Payroll trend','payroll.manage'],
  ['RECRUITMENT_FUNNEL','Hiring funnel','recruitment.manage'],['RECRUITMENT_OPEN_POSITIONS','Open positions','recruitment.manage'],['PERFORMANCE_GOALS','Goal completion','goal.manage.team'],
]as const;
const definition=(key:string)=>reportDefinitions.find(x=>x[0]===key);
const dateRange=(filters:Record<string,unknown>)=>({from:typeof filters.from==='string'?new Date(filters.from):undefined,to:typeof filters.to==='string'?new Date(filters.to):undefined});
export async function reportRows(prisma:PrismaClient,auth:Auth,key:string,filters:Record<string,unknown>={}){const def=definition(key);if(!def||!auth.permissions.includes(def[2]))throw Object.assign(new Error('This report is not available to your role.'),{status:403,code:'REPORT_FORBIDDEN'});const scoped=(await prisma.employee.findMany({where:employeeWhere(auth),select:{id:true}})).map(x=>x.id),range=dateRange(filters),dateFilter=range.from||range.to?{...(range.from?{gte:range.from}:{}),...(range.to?{lte:range.to}:{})}:undefined;
  if(key.startsWith('WORKFORCE_')){const employees=await prisma.employee.findMany({where:employeeWhere(auth),select:{id:true,employeeCode:true,firstName:true,lastName:true,status:true,employmentType:true,dateOfJoining:true,lastWorkingDay:true,department:{select:{name:true}},designation:{select:{title:true}}},orderBy:{employeeCode:'asc'}});if(key==='WORKFORCE_ATTRITION')return employees.filter(x=>['RESIGNED','TERMINATED'].includes(x.status));if(key==='WORKFORCE_NEW_HIRES')return employees.filter(x=>!dateFilter||( (!dateFilter.gte||x.dateOfJoining>=dateFilter.gte)&&(!dateFilter.lte||x.dateOfJoining<=dateFilter.lte)));if(key==='WORKFORCE_DEPARTMENTS')return Object.entries(Object.groupBy(employees,x=>x.department.name)).map(([department,items])=>({department,headcount:items?.length||0}));if(key==='WORKFORCE_EMPLOYMENT_TYPES')return Object.entries(Object.groupBy(employees,x=>x.employmentType)).map(([employmentType,items])=>({employmentType,headcount:items?.length||0}));return employees;}
  if(key.startsWith('ATTENDANCE_')){if(key==='ATTENDANCE_SHIFTS')return prisma.shiftAssignment.findMany({where:{companyId:auth.companyId,employeeId:{in:scoped}},select:{employeeId:true,effectiveFrom:true,effectiveTo:true,shift:{select:{name:true,code:true,startTime:true,endTime:true,isNightShift:true,isFlexible:true}}},orderBy:{effectiveFrom:'desc'}});const where={companyId:auth.companyId,employeeId:{in:scoped},...(dateFilter?{date:dateFilter}:{})};if(key==='ATTENDANCE_LATE')return prisma.attendanceRecord.findMany({where:{...where,lateMinutes:{gt:0}},select:{employeeId:true,date:true,status:true,clockInTime:true,lateMinutes:true}});if(key==='ATTENDANCE_ABSENCE')return prisma.attendanceRecord.findMany({where:{...where,status:'ABSENT'},select:{employeeId:true,date:true,status:true}});if(key==='ATTENDANCE_OVERTIME')return prisma.attendanceRecord.findMany({where:{...where,overtimeHours:{gt:0}},select:{employeeId:true,date:true,overtimeHours:true,workHours:true}});return prisma.attendanceRecord.findMany({where,select:{employeeId:true,date:true,status:true,workHours:true,lateMinutes:true,overtimeHours:true},orderBy:{date:'desc'},take:10000});}
  if(key.startsWith('LEAVE_')){const requests=await prisma.leaveRequest.findMany({where:{companyId:auth.companyId,employeeId:{in:scoped},...(dateFilter?{startDate:dateFilter}:{})},include:{leaveType:{select:{name:true,daysAllowedPerYear:true,carryForwardDays:true}}},orderBy:{startDate:'desc'}});if(key==='LEAVE_BALANCES')return Object.values(Object.groupBy(requests,x=>`${x.employeeId}:${x.leaveTypeId}`)).map(items=>{const first=items![0],used=items!.filter(x=>['PENDING','APPROVED'].includes(x.status)).reduce((n,x)=>n+x.totalDays,0);return{employeeId:first.employeeId,leaveType:first.leaveType.name,entitlement:first.leaveType.daysAllowedPerYear+first.leaveType.carryForwardDays,used,available:first.leaveType.daysAllowedPerYear+first.leaveType.carryForwardDays-used}});if(key==='LEAVE_TRENDS')return Object.entries(Object.groupBy(requests,x=>x.startDate.toISOString().slice(0,7))).map(([month,items])=>({month,requests:items?.length||0,days:items?.reduce((n,x)=>n+x.totalDays,0)||0}));return requests.map(x=>({employeeId:x.employeeId,leaveType:x.leaveType.name,startDate:x.startDate,endDate:x.endDate,days:x.totalDays,status:x.status}));}
  if(key.startsWith('PAYROLL_')){const runs=await prisma.payrollRun.findMany({where:{companyId:auth.companyId},include:{payslips:{select:{employeeId:true,grossSalary:true,totalDeductions:true,netSalary:true,calculationTrace:true}}},orderBy:{month:'desc'}});if(key==='PAYROLL_DEPARTMENT_COST'){const employees=await prisma.employee.findMany({where:{companyId:auth.companyId},select:{id:true,department:{select:{name:true}}}}),departments=new Map(employees.map(x=>[x.id,x.department.name]));return runs.flatMap(run=>Object.entries(Object.groupBy(run.payslips,x=>departments.get(x.employeeId)||'Unknown')).map(([department,items])=>({month:run.month,department,gross:items?.reduce((n,x)=>n+x.grossSalary,0)||0,net:items?.reduce((n,x)=>n+x.netSalary,0)||0})));}if(key==='PAYROLL_STATUTORY')return runs.map(run=>({month:run.month,status:run.status,totalDeductions:run.totalDeductions,employees:run.totalEmployees}));return runs.map(run=>({month:run.month,status:run.status,totalEmployees:run.totalEmployees,totalGross:run.totalGrossSalary,totalDeductions:run.totalDeductions,totalNet:run.totalNetPayout}));}
  if(key.startsWith('RECRUITMENT_')){if(key==='RECRUITMENT_OPEN_POSITIONS')return prisma.jobPosting.findMany({where:{companyId:auth.companyId,status:'OPEN'},select:{title:true,department:true,location:true,applicantCount:true,createdAt:true}});const applicants=await prisma.jobApplicant.findMany({where:{companyId:auth.companyId},select:{stage:true,appliedAt:true}});return Object.entries(Object.groupBy(applicants,x=>x.stage)).map(([stage,items])=>({stage,candidates:items?.length||0}));}
  return prisma.performanceGoal.findMany({where:{companyId:auth.companyId,employeeId:{in:scoped}},select:{employeeId:true,title:true,category:true,targetDate:true,progress:true,status:true},orderBy:{targetDate:'desc'}});
}
const flat=(value:unknown)=>value instanceof Date?value.toISOString():value&&typeof value==='object'?JSON.stringify(value):value??'';const xml=(v:unknown)=>String(flat(v)).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');const col=(n:number)=>{let s='';for(n++;n;n=Math.floor((n-1)/26))s=String.fromCharCode(65+(n-1)%26)+s;return s};
export function renderReport(rows:Record<string,unknown>[],format:'CSV'|'XLSX'|'PDF'){const headers=[...new Set(rows.flatMap(Object.keys))];if(format==='CSV'){const cell=(v:unknown)=>`"${String(flat(v)).replace(/"/g,'""')}"`;return{mime:'text/csv; charset=utf-8',extension:'csv',bytes:Buffer.from('\uFEFF'+[headers.map(cell).join(','),...rows.map(r=>headers.map(h=>cell(r[h])).join(','))].join('\r\n'))}}if(format==='PDF'){const doc=new jsPDF({orientation:'landscape'}),lines=[headers.join(' | '),...rows.map(r=>headers.map(h=>String(flat(r[h]))).join(' | '))];let y=12;doc.setFontSize(7);for(const line of lines){const wrapped=doc.splitTextToSize(line,275);if(y+wrapped.length*4>195){doc.addPage();y=12}doc.text(wrapped,10,y);y+=wrapped.length*4}return{mime:'application/pdf',extension:'pdf',bytes:Buffer.from(doc.output('arraybuffer'))}}const all=[headers,...rows.map(r=>headers.map(h=>r[h]))],sheet=all.map((r,ri)=>`<row r="${ri+1}">${r.map((v,ci)=>typeof v==='number'?`<c r="${col(ci)}${ri+1}"><v>${v}</v></c>`:`<c r="${col(ci)}${ri+1}" t="inlineStr"><is><t>${xml(v)}</t></is></c>`).join('')}</row>`).join(''),files={'[Content_Types].xml':strToU8('<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/></Types>'),'_rels/.rels':strToU8('<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>'),'xl/workbook.xml':strToU8('<?xml version="1.0"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="OrbitHR Report" sheetId="1" r:id="rId1"/></sheets></workbook>'),'xl/_rels/workbook.xml.rels':strToU8('<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/></Relationships>'),'xl/worksheets/sheet1.xml':strToU8(`<?xml version="1.0"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>${sheet}</sheetData></worksheet>`)};return{mime:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',extension:'xlsx',bytes:Buffer.from(zipSync(files,{level:6}))}}
export function createReportRouter(prisma:PrismaClient,authenticate:RequestHandler){const router=Router(),fail=(res:Response,status:number,code:string,message:string)=>res.status(status).json({error:{code,message}});router.use('/reports',authenticate);router.get('/reports/catalog',(req:Req,res)=>res.json({data:reportDefinitions.filter(x=>req.auth!.permissions.includes(x[2])).map(([key,name])=>({key,name})),meta:{requestId:req.requestId}}));router.get('/reports/exports/history',async(req:Req,res,next)=>{try{res.json({data:await prisma.reportExport.findMany({where:{companyId:req.auth!.companyId,userId:req.auth!.id},orderBy:{createdAt:'desc'},take:100}),meta:{requestId:req.requestId}})}catch(e){next(e)}});router.get('/reports/:key',async(req:Req,res,next)=>{try{const filters=z.record(z.string(),z.unknown()).parse(req.query),rows=await reportRows(prisma,req.auth!,String(req.params.key).toUpperCase(),filters);res.json({data:{key:String(req.params.key).toUpperCase(),rows,truncated:false},meta:{requestId:req.requestId}})}catch(e){next(e)}});router.post('/reports/:key/exports',async(req:Req,res,next)=>{try{const body=z.object({format:z.enum(['CSV','XLSX','PDF']),filters:z.record(z.string(),z.unknown()).default({})}).parse(req.body),key=String(req.params.key).toUpperCase(),rows=await reportRows(prisma,req.auth!,key,body.filters),record=await prisma.reportExport.create({data:{companyId:req.auth!.companyId,userId:req.auth!.id,reportKey:key,format:body.format,filters:body.filters,status:'COMPLETED',rowCount:rows.length,completedAt:new Date()}}),file=renderReport(rows as Record<string,unknown>[],body.format);await prisma.auditLog.create({data:{companyId:req.auth!.companyId,userId:req.auth!.id,userName:req.auth!.id,userRole:req.auth!.role,action:'REPORT_EXPORTED',category:'DATA_EXPORT',details:`${key} ${body.format} export ${record.id} generated with ${rows.length} rows.`,ipAddress:req.ip||'unknown'}});res.setHeader('content-type',file.mime);res.setHeader('content-disposition',`attachment; filename="orbithr-${key.toLowerCase()}-${record.id}.${file.extension}"`);res.setHeader('x-report-export-id',record.id);return res.send(file.bytes)}catch(e){next(e)}});return router}
