CREATE TYPE "ReportExportStatus" AS ENUM ('PENDING','COMPLETED','FAILED','EXPIRED');
CREATE TYPE "DocumentVerificationStatus" AS ENUM ('PENDING','VERIFIED','REJECTED','EXPIRED');
CREATE TABLE "EmployeeDocument" ("id" TEXT NOT NULL,"companyId" TEXT NOT NULL,"employeeId" TEXT NOT NULL,"documentType" TEXT NOT NULL,"title" TEXT NOT NULL,"objectKey" TEXT NOT NULL,"fileName" TEXT NOT NULL,"mimeType" TEXT NOT NULL,"sizeBytes" INTEGER NOT NULL,"issueDate" DATE,"expiryDate" DATE,"verificationStatus" "DocumentVerificationStatus" NOT NULL DEFAULT 'PENDING',"verifiedById" TEXT,"verifiedAt" TIMESTAMP(3),"rejectionReason" TEXT,"retentionUntil" DATE,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "EmployeeDocument_pkey" PRIMARY KEY ("id"));
CREATE TABLE "SavedReport" ("id" TEXT NOT NULL,"companyId" TEXT NOT NULL,"userId" TEXT NOT NULL,"name" TEXT NOT NULL,"reportKey" TEXT NOT NULL,"filters" JSONB NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "SavedReport_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ReportExport" ("id" TEXT NOT NULL,"companyId" TEXT NOT NULL,"userId" TEXT NOT NULL,"reportKey" TEXT NOT NULL,"format" TEXT NOT NULL,"filters" JSONB NOT NULL,"status" "ReportExportStatus" NOT NULL DEFAULT 'PENDING',"rowCount" INTEGER,"objectKey" TEXT,"error" TEXT,"expiresAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"completedAt" TIMESTAMP(3),CONSTRAINT "ReportExport_pkey" PRIMARY KEY ("id"));
CREATE TABLE "LoginAttempt" ("id" TEXT NOT NULL,"companyId" TEXT,"email" TEXT NOT NULL,"userId" TEXT,"success" BOOLEAN NOT NULL,"reason" TEXT,"ipAddress" TEXT NOT NULL,"userAgent" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "LoginAttempt_pkey" PRIMARY KEY ("id"));
CREATE TABLE "AiInteraction" ("id" TEXT NOT NULL,"companyId" TEXT NOT NULL,"userId" TEXT NOT NULL,"prompt" TEXT NOT NULL,"intent" TEXT NOT NULL,"answer" TEXT NOT NULL,"sources" JSONB NOT NULL,"proposedAction" JSONB,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "AiInteraction_pkey" PRIMARY KEY ("id"));
CREATE INDEX "EmployeeDocument_companyId_expiryDate_idx" ON "EmployeeDocument"("companyId","expiryDate");
CREATE INDEX "EmployeeDocument_employeeId_documentType_idx" ON "EmployeeDocument"("employeeId","documentType");
CREATE INDEX "SavedReport_companyId_userId_idx" ON "SavedReport"("companyId","userId");
CREATE INDEX "ReportExport_companyId_createdAt_idx" ON "ReportExport"("companyId","createdAt");
CREATE INDEX "LoginAttempt_email_createdAt_idx" ON "LoginAttempt"("email","createdAt");
CREATE INDEX "LoginAttempt_companyId_createdAt_idx" ON "LoginAttempt"("companyId","createdAt");
CREATE INDEX "AiInteraction_companyId_createdAt_idx" ON "AiInteraction"("companyId","createdAt");
ALTER TABLE "EmployeeDocument" ADD CONSTRAINT "EmployeeDocument_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "EmployeeDocument" ADD CONSTRAINT "EmployeeDocument_employeeId_fkey" FOREIGN KEY ("employeeId") REFERENCES "Employee"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "SavedReport" ADD CONSTRAINT "SavedReport_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "SavedReport" ADD CONSTRAINT "SavedReport_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ReportExport" ADD CONSTRAINT "ReportExport_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ReportExport" ADD CONSTRAINT "ReportExport_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "LoginAttempt" ADD CONSTRAINT "LoginAttempt_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "AiInteraction" ADD CONSTRAINT "AiInteraction_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "AiInteraction" ADD CONSTRAINT "AiInteraction_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
