import React, { useCallback, useEffect, useState } from 'react';
import { Check, Clock3, Inbox, MessageSquare, RefreshCw, X } from 'lucide-react';
import { api } from '../../services/api';
import type { ApprovalInboxItem, WorkflowInstance } from '../../types';
import { useToast } from '../../context/ToastContext';
import { EmptyState } from '../../components/ui/EmptyState';

export const ApprovalInboxPage: React.FC = () => {
  const toast = useToast(); const [tab, setTab] = useState<'inbox'|'mine'>('inbox'); const [inbox, setInbox] = useState<ApprovalInboxItem[]>([]); const [mine, setMine] = useState<WorkflowInstance[]>([]); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { setBusy(true); try { const [assigned, requests] = await Promise.all([api.getApprovalInbox(), api.getMyRequests()]); setInbox(assigned); setMine(requests); } catch (error) { toast.error('Approvals could not be loaded', error instanceof Error ? error.message : 'Unknown error'); } finally { setBusy(false); } }, [toast]);
  useEffect(() => { void load(); }, [load]);
  const act = async (instanceId: string, action: 'APPROVE'|'REJECT'|'COMMENT') => { const comment = window.prompt(action === 'COMMENT' ? 'Add comment' : `${action === 'APPROVE' ? 'Approval' : 'Rejection'} note (optional)`) || undefined; if (action === 'COMMENT' && !comment) return; setBusy(true); try { await api.actOnWorkflow(instanceId, action, comment); toast.success(action === 'COMMENT' ? 'Comment added' : `Request ${action.toLowerCase()}d`); await load(); } catch (error) { toast.error('Action failed', error instanceof Error ? error.message : 'Unknown error'); } finally { setBusy(false); } };
  const statusClass = (status: string) => status === 'APPROVED' ? 'text-emerald-300 bg-emerald-500/10' : status === 'REJECTED' ? 'text-rose-300 bg-rose-500/10' : 'text-amber-300 bg-amber-500/10';
  return <div className="neo-page space-y-5"><div className="flex items-center justify-between border-b border-slate-800 pb-4"><div><h1 className="text-2xl font-bold flex items-center gap-2"><Inbox className="text-brand-400"/>Approval Inbox</h1><p className="text-xs text-slate-400 mt-1">One queue for leave, expense, attendance, payroll, documents, and employee requests.</p></div><button onClick={() => void load()} disabled={busy} className="p-2 rounded-xl border border-slate-700"><RefreshCw className={`w-4 h-4 ${busy?'animate-spin':''}`}/></button></div>
  <div className="flex gap-2"><button onClick={()=>setTab('inbox')} className={`px-4 py-2 rounded-xl text-xs font-bold ${tab==='inbox'?'bg-brand-500':'bg-slate-900 border border-slate-800 text-slate-400'}`}>Assigned to me ({inbox.length})</button><button onClick={()=>setTab('mine')} className={`px-4 py-2 rounded-xl text-xs font-bold ${tab==='mine'?'bg-brand-500':'bg-slate-900 border border-slate-800 text-slate-400'}`}>My requests ({mine.length})</button></div>
  {tab === 'inbox' ? <div className="space-y-3">{inbox.map(item=><article key={item.id} className="bg-slate-900 border border-slate-800 rounded-2xl p-5 flex flex-col lg:flex-row lg:items-center gap-4 justify-between"><div><div className="flex items-center gap-2"><span className="text-[10px] font-bold px-2 py-1 bg-indigo-500/10 text-indigo-300 rounded-lg">{item.instance.module}</span><span className="text-xs text-slate-500">Step {item.sequence}: {item.step.name}</span></div><h2 className="font-bold mt-2">{item.instance.title}</h2><p className="text-xs text-slate-400 mt-1">{item.instance.summary || 'No summary provided.'}</p>{item.dueAt&&<p className="text-[11px] text-amber-300 mt-2 flex gap-1 items-center"><Clock3 className="w-3 h-3"/>Due {new Date(item.dueAt).toLocaleString()}</p>}</div><div className="flex gap-2"><button disabled={busy} onClick={()=>void act(item.instance.id,'COMMENT')} className="p-2.5 rounded-xl border border-slate-700 text-slate-300" title="Comment"><MessageSquare className="w-4 h-4"/></button><button disabled={busy} onClick={()=>void act(item.instance.id,'REJECT')} className="px-3 py-2 rounded-xl bg-rose-500/10 text-rose-300 flex gap-1 items-center"><X className="w-4 h-4"/>Reject</button><button disabled={busy} onClick={()=>void act(item.instance.id,'APPROVE')} className="px-3 py-2 rounded-xl bg-emerald-500 text-white flex gap-1 items-center"><Check className="w-4 h-4"/>Approve</button></div></article>)}{!inbox.length&&<EmptyState title="Approval queue is clear" description="Requests assigned to you will appear here with their due dates and workflow steps." icon={Check}/>}</div> : <div className="space-y-3">{mine.map(item=><article key={item.id} className="bg-slate-900 border border-slate-800 rounded-2xl p-5 flex justify-between gap-4"><div><span className="text-[10px] text-brand-300">{item.module}</span><h2 className="font-bold mt-1">{item.title}</h2><p className="text-xs text-slate-500 mt-1">Submitted {new Date(item.submittedAt).toLocaleString()}</p></div><span className={`h-fit px-2.5 py-1 rounded-lg text-[11px] font-bold ${statusClass(item.status)}`}>{item.status}</span></article>)}{!mine.length&&<EmptyState title="No requests submitted" description="Your leave, attendance, expense and payroll requests will be tracked here." icon={Inbox}/>}</div>}
  </div>;
};
